#!/usr/bin/env ruby

#Gabriela Limonta 10-10385
#John Delgado 10-10196

require 'Lexer'

# En el main se llama a los metodos declarados anteriormente
def main
  # Leemos la entrada del archivo
  entrada = File::read(ARGV[0])

  # Creamos un nuevo lexer con esta entrada
  lexer = Lexer::new entrada
  # Mientras el lexer siga leyendo e identificando tokens o errores en el texto de entrada el programa corre
  t = false
  while (!t) do
    t = lexer.yylex.nil?
  end

  # Finalmente se imprime el lexer.
  puts lexer
end

main
