#!/usr/bin/env ruby

#Gabriela Limonta 10-10385
#John Delgado 10-10196

require 'Lexer'
require 'Parser'

# En el main se llama a los metodos declarados anteriormente
def main
  # Leemos la entrada del archivo
  entrada = File::read(ARGV[0])

  # Creamos un nuevo lexer con esta entrada, se lo pasamos al parser que
  # genera el ast y se imprime por pantalla el mismo.
  begin
    # Creamos el ast
    ast = Parser::new.parse(Lexer::new entrada)
    # Si no es nil, es porque no hubo errores lexicográficos
    # de modo que imprimimos el ast, si ast es nil es porque
    # hubo errores lexicográficos por lo que no imprimiriamos
    # el ast.
    if (nil != ast) then puts ast end
  rescue ErrorSintactico => e
    puts e
  end
end

main
