#!/usr/bin/env ruby
module Rangex; end

#Gabriela Limonta 10-10385
#John Delgado 10-10196

require 'Lexer'
require 'Parser'
require 'SymTable'

# En el main se llama a los metodos declarados anteriormente
def main
  $ErroresContexto = []

  # Leemos la entrada del archivo
  entrada = File::read(ARGV[0])

  # Creamos un nuevo lexer con esta entrada, se lo pasamos al parser que
  # genera el ast y se imprime por pantalla el mismo.
  begin
    # Creamos el ast
    ast = Parser::new.parse(Lexer::new entrada)
    ast.check
    unless $ErroresContexto.empty?
      puts $ErroresContexto
    else
      puts ast
    end
  rescue LexerException => l
    puts l.lexer
  rescue RedefinirError => r
    puts r
  rescue UpdateError => s
    puts s
  rescue DeleteError => d
    puts d
  rescue ErrorSintactico => e
    puts e
  end
end

main
